joint:
  names: [pan]
motion:
  names: [left1,zero1,left2,zero2,left3,zero3]
  # right:
  #   step: [-3.14]  # radian
  #   time_from_start: 2.0  # sec
  left1:
    step: [1.04]
    time_from_start: 1.5
  zero1:
    step: [0.0]
    time_from_start: 3.0
  left2:
    step: [1.04]
    time_from_start: 4.5
  zero2:
    step: [0.0]
    time_from_start: 6.0    
  left3:
    step: [1.04]
    time_from_start: 7.5
  zero3:
    step: [0.0]
    time_from_start: 9.0   