#Configuation for robot odometry EKF
frequency: 60
two_d_mode: true
publish_tf: false

# map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

transform_time_offset: 0.0
transform_timeout : 0.1

# Complete the odom0 configuration
odom0: odom
odom0_config: [false, false,  false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]

odom0_differential: false
 
# Complete the imu0 configuration
imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, false, false]                    

imu0_differential: false
